TEXTS = {
    "es": {
        "choose_language": "Elegí idioma / Choose language: [es/en]: ",
        "invalid_language": "Idioma inválido. Escribí 'es' para español o 'en' para inglés.",
        "title": "\n=== Sistema de orientación sobre dolor de cabeza ===",
        "disclaimer": "Este sistema es educativo y no reemplaza una consulta médica.",
        "yes_no_suffix": " (si/no): ",
        "invalid_yes_no": "Respuesta inválida. Escribí 'si' o 'no'.",
        "final_result": "\nResultado final: ",
        "answers_title": "\nResumen de respuestas:",
        "warnings_title": "Advertencias sobre las respuestas:",
        "yes": "Sí",
        "no": "No",

        "dx_migraine_aura": "Compatible con migraña con aura",
        "dx_migraine_no_aura": "Compatible con migraña sin aura",
        "dx_tension": "Compatible con cefalea tensional",
        "dx_inconclusive": "No concluyente",

        "aura_any": "Antes del dolor de cabeza, ¿tuviste cambios visuales, hormigueo o dificultad para hablar?",
        "aura_gradual": "¿Esos síntomas aparecieron de a poco en varios minutos?",
        "aura_duration": "¿Esos síntomas duraron entre 5 y 60 minutos?",
        "aura_followed_headache": "¿Después de esos síntomas empezó el dolor de cabeza en menos de 1 hora?",

        "migraine_duration": "¿El dolor de cabeza duró entre 4 horas y 3 días?",
        "unilateral": "¿El dolor estuvo más de un solo lado de la cabeza?",
        "pulsating": "¿El dolor latía o se sentía como pulsaciones?",
        "moderate_severe": "¿El dolor fue moderado o fuerte?",
        "worse_activity": "¿Caminar, moverte o subir escaleras lo empeoraba?",
        "nausea": "¿Tuviste náuseas o ganas de vomitar?",
        "light_sensitive": "¿La luz te molestaba?",
        "sound_sensitive": "¿El ruido te molestaba?",

        "tension_duration": "¿El dolor duró entre 30 minutos y 7 días?",
        "bilateral": "¿El dolor estuvo en ambos lados de la cabeza?",
        "pressure": "¿El dolor se sentía como presión o peso, y no como latidos?",
        "mild_moderate": "¿El dolor fue leve o moderado?",

        "label_aura_any": "Síntomas de aura antes del dolor",
        "label_aura_gradual": "Aura apareció gradualmente",
        "label_aura_duration": "Aura duró 5 a 60 minutos",
        "label_aura_followed_headache": "Aura seguida por dolor de cabeza",
        "label_migraine_duration": "Duración compatible con migraña",
        "label_unilateral": "Dolor de un solo lado",
        "label_pulsating": "Dolor pulsátil",
        "label_moderate_severe": "Dolor moderado o fuerte",
        "label_worse_activity": "Empeora con actividad",
        "label_nausea": "Náuseas o vómitos",
        "label_light_sensitive": "Molestia con la luz",
        "label_sound_sensitive": "Molestia con el ruido",
        "label_tension_duration": "Duración compatible con tensión",
        "label_bilateral": "Dolor en ambos lados",
        "label_pressure": "Dolor opresivo / tipo presión",
        "label_mild_moderate": "Dolor leve o moderado",

        "contradiction_side": "Marcaste que el dolor fue de un solo lado y también de ambos lados.",
        "contradiction_intensity": "Marcaste que el dolor fue leve/moderado y también moderado/fuerte.",
    },

    "en": {
        "choose_language": "Choose language / Elegí idioma: [en/es]: ",
        "invalid_language": "Invalid language. Type 'es' for Spanish or 'en' for English.",
        "title": "\n=== Headache screening system ===",
        "disclaimer": "This system is educational and does not replace medical care.",
        "yes_no_suffix": " (yes/no): ",
        "invalid_yes_no": "Invalid answer. Please type 'yes' or 'no'.",
        "final_result": "\nFinal result: ",
        "answers_title": "\nAnswer summary:",
        "warnings_title": "Warnings about the answers:",
        "yes": "Yes",
        "no": "No",

        "dx_migraine_aura": "Compatible with migraine with aura",
        "dx_migraine_no_aura": "Compatible with migraine without aura",
        "dx_tension": "Compatible with tension-type headache",
        "dx_inconclusive": "Inconclusive",

        "aura_any": "Before the headache, did you have visual changes, tingling, or trouble speaking?",
        "aura_gradual": "Did those symptoms build up gradually over several minutes?",
        "aura_duration": "Did those symptoms last between 5 and 60 minutes?",
        "aura_followed_headache": "Did the headache start within 1 hour after those symptoms?",

        "migraine_duration": "Did the headache last between 4 hours and 3 days?",
        "unilateral": "Was the pain mostly on one side of the head?",
        "pulsating": "Did the pain feel like throbbing or pulsing?",
        "moderate_severe": "Was the pain moderate or strong?",
        "worse_activity": "Did walking, moving, or climbing stairs make it worse?",
        "nausea": "Did you feel nauseous or like vomiting?",
        "light_sensitive": "Did light bother you?",
        "sound_sensitive": "Did sound bother you?",

        "tension_duration": "Did the pain last between 30 minutes and 7 days?",
        "bilateral": "Was the pain on both sides of the head?",
        "pressure": "Did the pain feel like pressure or tightness rather than throbbing?",
        "mild_moderate": "Was the pain mild or moderate?",

        "label_aura_any": "Aura symptoms before headache",
        "label_aura_gradual": "Aura appeared gradually",
        "label_aura_duration": "Aura lasted 5 to 60 minutes",
        "label_aura_followed_headache": "Aura followed by headache",
        "label_migraine_duration": "Migraine-like duration",
        "label_unilateral": "One-sided pain",
        "label_pulsating": "Pulsating pain",
        "label_moderate_severe": "Moderate or strong pain",
        "label_worse_activity": "Worse with activity",
        "label_nausea": "Nausea or vomiting",
        "label_light_sensitive": "Sensitive to light",
        "label_sound_sensitive": "Sensitive to sound",
        "label_tension_duration": "Tension-like duration",
        "label_bilateral": "Pain on both sides",
        "label_pressure": "Pressure / tightness pain",
        "label_mild_moderate": "Mild or moderate pain",

        "contradiction_side": "You marked the pain as one-sided and also on both sides.",
        "contradiction_intensity": "You marked the pain as mild/moderate and also moderate/strong.",
    }
}